# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is 2024.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledge reports with the mains topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst

vacation_research_task:
  description: >
    1. Research 10 tourist destinations to visit in each of the following stops: {stops}.
       Make sure you find up to date information given the current year is 2024.
    2. Research pricing information for where to stay overnight in each of the stops,
       and where to eat in each of the stops, as well as time taken to get there by {vehicle}.
    3. Generate a comprehensive report of all of these findings.
  expected_output: >
    A report of 10 tourist destinations to visit in each of the {stops} along with information about 
    the significance of the tourist destination, pricing, time to reach by {vehicle}, and inter-location
    travel times, recommended time to spend there, and recommended places to stay for overnight lodging. 
  agent: vacation_researcher

vacation_planning_task:
  description: >
    1. Review the report generated by the Vacation Researcher.
    2. Make selections based on the findings that minimize cost, travel time, and maximize significance.
    3. Generate 3 fully fledged detailed reports based on the findings that emphasize variety in all of the
    key metrics outlined in the report generated by the Vacation Researcher.
  expected_output: >
    3 Fully fledged detailed reports based on the reports generated by the Vacation Researcher and selections
    made by the Vacation Planning Specialist.
  agent: vacation_planning_specialist
  
vacation_day_breakdown_task:
  description: >
    1. Review the reports generated by the Vacation Planning Specialist.
    2. Generate a small summary in Markdown format outlining the significance of the day 
    plan based on the report generated by the Vacation Planning specialist. 
    3. Generate Hour by Hour breakdowns of the day in Markdown format, below the summary.
    4. Do this for all 3 reports.
  expected_output: >
    3 Hour by Hour breakdowns that include a small summary of the significance of the day in Markdown format.
  agent: vacation_day_breakdown_planner
